### ISSUE TITLE
Fail to generator a builder for schemas/aggregate/cosignature.cats

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catbuffer#24]
import "types.h" should be import "types.cats"

python3 main.py --schema schemas/aggregate/cosignature.cats --generator cpp_builder
Traceback (most recent call last):
  File "/Users/tbdev/code/catbuffer/catparser/CatsParser.py", line 31, in process_line
    self._process_line(line)
  File "/Users/tbdev/code/catbuffer/catparser/CatsParser.py", line 90, in _process_line
    self.import_resolver(parse_result.import_file)
  File "main.py", line 23, in _process_import_file
    self._process_file(filename)
  File "main.py", line 28, in _process_file
    with open(filename) as input_file:
FileNotFoundError: [Errno 2] No such file or directory: './schemas/types.h'

**Comment by Jaguar0625** [comment]
Fixed in 199c607.
